New upstream version 3.17

diff --git a/regress-driver b/regress-driver
--- a/regress-driver
+++ b/regress-driver
@@ -14,6 +14,9 @@ else
     GPSD_HOME=`dirname $0`
 fi
 
+# sed may choke on binary data with some LANG settings
+unset LANG
+
 # Arrange to call a gpsfake in the source directory without fuss.
 if [ -z ${PYTHON} ]; then
     PYTHON="python2"
@@ -45,10 +48,12 @@ opts=""
 logfile=""
 help="0"
 baton=false
-while getopts cl:sStbuvo:h opt
+quiet=false
+quieter=false
+while getopts cl:sStbuvo:qQh opt
 do
     case $opt in
-	c) testing=clientlib ;;	# Can be 'daemon'
+	c) testing=clientlib ;;	# 'client' rather than the daemon
 	l) logfile=$OPTARG ;;	# Logfile to save diffs to
 	s) mode=regress ;;	# Run regression tests
 	S) mode=slowregress ;;	# Run regression tests with big delays
@@ -57,7 +62,9 @@ do
 	u) opts="$opts -u" ;;	# Force UDP
 	v) mode=view ;;		# View result of generating a check file
 	o) opts="$opts $OPTARG" ;;	# Pass options to gpsfake
-	h) help="1"
+	q) quiet=true ;;	# Suppress header/trailer messages
+	Q) quiet=true; quieter=true ;;	# Suppress all success chatter
+	h) help="1" ;;
     esac
 done
 shift $(($OPTIND - 1))
@@ -68,15 +75,17 @@ then
 	echo
 	echo "Regression test driver script"
 	echo "-h  - this help"
-	echo "-c  - can be 'daemon'"
+	echo "-c  - test with 'client' rather than the daemon"
 	echo "-l <filename>  - where to log diffs to"
 	echo "-s  - run regression tests"
 	echo "-S  - run regression tests with realistic timing delays"
 	echo "-t <ots>  - Run regression tests w/baton"
 	echo "-b  - Rebuild regression check files"
-	echo "-u - Force UDP"
+	echo "-u  - Force UDP"
 	echo "-v  - view result of generating a check file"
 	echo "-o <opt> - Pass options to gpsfake"
+	echo "-q  - Suppress header/trailer messages"
+	echo "-Q  - Suppress all success chatter"
 	echo
 
 	exit 0
@@ -93,7 +102,7 @@ GPSFILTER="sed -e /^gpsd:/d -e /^gpsfake/d -e /GPS-DATA/d -e /WATCH/d -e /DEVICE
 
 # Use ALTFILTER to set up custom filtering when a regression test fails
 # This example filters out altitude and some fields computed by gpsd's error
-# modeling - these are fragile in the prsence of changes to the fix-buffering
+# modeling - these are fragile in the presence of changes to the fix-buffering
 # logic. Note that as the last attribute mode needs to be handled differently.
 #ALTFILTER="-e s/\"alt\":[^,]*,// -e s/\"ep[vhs]\":[-+0-9.]*// -e s/,\"mode\":[^}]*//"
 
@@ -114,16 +123,21 @@ then
     opts="$opts -S"
 fi
 
+if [ $quieter = true ]
+then
+    opts="$opts -q"
+fi
+
 case $mode in
     regress|slowregress)
-        echo "Testing the $testing..." >&2
+        [ $quiet = true ] || echo "Testing the $testing..." >&2
         errors=0; total=0; notfound=0;error_list="";
         for f in $*; do
 	    if [ -r $f.chk ]
 	    then
 		trap 'rm -f ${TMP}/test-$$.chk; exit $errors' EXIT HUP INT TERM
 		case $testing in
-		daemon) TMPDIR=${TMP} ${PYTHON} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} ${ALTFILTER} >${TMP}/test-$$.chk ;;
+		daemon) TMPDIR=${TMP} ${PYTHON} ${PYTHON_COVERAGE} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} ${ALTFILTER} >${TMP}/test-$$.chk ;;
 		clientlib) ${GPSD_HOME}/test_libgps -b <${f} >${TMP}/test-$$.chk ;;
 		esac
 		if [ "${ALTFILTER}" ]
@@ -137,7 +151,10 @@ case $mode in
 		fi
 		if test -s ${TMP}/diff-$$ ; then
 		    errors=`expr $errors + 1`;
-                    error_list="$error_list \"${f}\""
+		    error_list="$error_list \"${f}\""
+		    if ! test -s ${TMP}/test-$$.chk ; then
+			echo " Output missing for ${f}" >${TMP}/diff-$$
+		    fi
 		    if [ -z "$logfile" ]
 		    then
 			cat ${TMP}/diff-$$
@@ -163,26 +180,31 @@ case $mode in
             echo "================================================================"
             status=1;
         else
-            echo "Regression test successful: no errors in $total tests ($notfound not found).";
+            if [ $quiet = true ] && [ $total -eq 1 ] && [ $notfound -eq 0 ]
+            then
+                [ $quieter = true ] || echo "Regression test $1 successful"
+            else
+                echo "Regression test successful: no errors in $total tests ($notfound not found).";
+            fi
             status=0;
         fi
         ;;
     build)
-	echo "Rebuilding $testing regressions..." >&2
+	[ $quiet = true ] || echo "Rebuilding $testing regressions..." >&2
         for f in $*; do
 	    case $testing in
-            daemon) ${PYTHON} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} >${f}.chk;;
+            daemon) ${PYTHON} ${PYTHON_COVERAGE} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} >${f}.chk;;
 	    clientlib) ${GPSD_HOME}/test_libgps -b <${f} >${f}.chk ;;
             esac
         done
         status=0
         ;;
     view)
-        echo "Viewing..." >&2
+        [ $quiet = true ] || echo "Viewing..." >&2
         for f in $*; do
 	    case $testing in
-            daemon) ${PYTHON} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} ;;
-            clientlib) ${GPSD_HOME}/libgps -b <${f} ;;
+            daemon) ${PYTHON} ${PYTHON_COVERAGE} ${GPSD_HOME}/gpsfake -s 38400 -1 -p $opts ${f} | ${GPSFILTER} ;;
+            clientlib) ${GPSD_HOME}/test_libgps -b <${f} ;;
             esac
         done
         status=0
@@ -192,10 +214,11 @@ esac
 # See starttime above
 endtime=`date +"%s * 1000000000 + %N" | sed '/+ N/s///' 2>/dev/null`
 
-if [ "$starttime" -a "$endtime" ]
+if [ $quiet = false ] && [ "$starttime" -a "$endtime" ]
 then
-    echo -n "Elapsed time: "
-    echo "scale=2; (${endtime} - ${starttime}) / 1000000000" | bc
+    # Avoid using -n here since some shells don't support it.
+    echo "Elapsed time:" \
+    $(echo "scale=2; (${endtime} - ${starttime}) / 1000000000" | bc) >&2
 fi
 
 rm -fr ${TMP}
