Run gpsd as user _gpsd in group dialout.

diff --git a/debian/gpsd.postinst b/debian/gpsd.postinst
--- a/debian/gpsd.postinst
+++ b/debian/gpsd.postinst
@@ -27,6 +27,21 @@ if [ "$1" = "configure" ] ; then
     fi
 
 
+    echo "Creating/updating _gpsd user account..."
+    adduser --system --ingroup dialout --home /run/gpsd \
+            --gecos "GPSD system user" --shell /bin/false \
+            --quiet --disabled-password _gpsd || {
+        # adduser failed. Why?
+        if getent passwd _gpsd >/dev/null ; then
+            echo "Non-system user _gpsd found. I will not overwrite a non-system" >&2
+            echo "user.  Remove the user and reinstall gpsd." >&2
+            exit 1
+        fi
+        # unknown adduser error, simply exit
+        exit 1
+    }
+
+
 fi
 
 #DEBHELPER#
diff --git a/debian/gpsd.postrm b/debian/gpsd.postrm
--- a/debian/gpsd.postrm
+++ b/debian/gpsd.postrm
@@ -6,6 +6,15 @@ set -e
 case "$1" in
     purge)
 	[ ! -f /etc/default/gpsd ] || rm /etc/default/gpsd
+
+        if [ -x "$(command -v deluser)" ]; then
+            deluser --quiet --system _gpsd > /dev/null || true
+        else
+            echo >&2 "not removing _gpsd system account because deluser command was not found"
+        fi
+
+        rm -rf /run/gpsd
+
     ;;
 
     remove|upgrade|failed-upgrade|abort-install|disappear|abort-upgrade)
